name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Frontend setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      # Backend setup
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Install backend dependencies and build
        run: |
          cd backend
          mvn clean install

      # Docker Compose
      - name: Build and run Docker Compose services
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d
          
      # Optional: Run any additional checks or tests inside containers
      - name: Run additional tests
        run: |
          docker-compose -f docker-compose.yml exec frontend npm test
          docker-compose -f docker-compose.yml exec backend mvn test

      # Optioneel: Push Docker images to Docker Hub
      - name: Push Docker images
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose -f docker-compose.yml push

      - name: Tear down Docker Compose services
        run: |
          docker-compose -f docker-compose.yml down
